#!/usr/bin/env bash

NORMAL='\033[0m'
GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'

marker="${BLUE}==>${NORMAL}"
status="…"
status_good="${GREEN}✔${NORMAL}"
status_bad="${RED}✘${NORMAL}"

function bootstrap-homebrew () {
  # Check for Homebrew
  printf "%b\r" "$marker Checking for Homebrew installation - $status"
  if [[ ! -e "$(command -v brew)" ]]; then
    printf "%b\n" "$marker Checking for Homebrew installation - $status_bad"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
    printf "%b\n" "$marker Checking for Homebrew installation - $status_good"
    brew upgrade > /dev/null
  fi
}

bootstrap-homebrew
