#!/bin/bash

# https://sourceware.org/gdb/wiki/PermissionsDarwin

security find-certificate -c gdb-cert
security find-certificate -p -c gdb-cert | openssl x509 -checkend 0
security find-certificate -p -c gdb-cert |openssl x509 -noout -text

security dump-trust-settings -d

echo '<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.cs.debugger</key>
    <true/>
</dict>
</plist>
</pre>' >> gdb-entitlement.xml

codesign --entitlements gdb-entitlement.xml -fs gdb-cert $(which gdb)
codesign -vv $(which gdb)
codesign -d --entitlements - $(which gdb)

echo "GDB Code Signed! Please Restart Computer"
rm gdb-entitlement.xml

echo "set startup-with-shell off" >> ~/.gdbinit
