tap "caryll/tap"
tap "d12frosted/emacs-plus"
tap "daviderestivo/emacs-head"
tap "dunn/emacs"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "idaholab/moose"
cask "xquartz"
brew "automake"
brew "bash"
brew "libffi"
brew "glib"
brew "cairo"
brew "ccache"
brew "coreutils"
brew "curl"
brew "dbus", restart_service: true
brew "direnv"
brew "doxygen"
brew "fd"
brew "fish"
brew "openssl"
brew "pango"
brew "fontforge"
brew "fzf"
brew "git"
brew "gnutls"
brew "libgpg-error"
brew "gnupg"
brew "gmime"
brew "hunspell"
brew "ispell"
brew "isync"
brew "jags"
brew "pandoc"
brew "jupyterlab"
brew "libfixposix"
brew "llvm"
brew "lsd"
brew "mas"
brew "msmtp"
brew "xapian"
brew "mu"
brew "nmap"
brew "node"
brew "talloc"
brew "zlib"
brew "notmuch", args: ["HEAD"]
brew "pkg-config"
brew "poppler"
brew "pyenv"
brew "pyenv-virtualenv", args: ["HEAD"]
brew "r"
brew "ripgrep"
brew "sbcl"
brew "shfmt"
brew "sphinx-doc"
brew "stow"
brew "texinfo"
brew "toilet"
brew "trash"
brew "tree"
brew "ttfautohint"
brew "vdirsyncer"
brew "wget"
brew "wine"
brew "winetricks"
brew "youtube-dl"
brew "zsh", args: ["HEAD"]
brew "caryll/tap/otfcc-mac64"
brew "daviderestivo/emacs-head/emacs-head", args: ["HEAD", "with-cocoa", "with-ctags", "with-dbus", "with-imagemagick", "with-jansson", "with-mailutils", "with-modern-icon-sjrmanning", "with-no-frame-refocus", "with-pdumper", "with-xwidgets"]
cask "alacritty"
cask "coconutbattery"
cask "contexts"
cask "font-firacode-nerd-font"
cask "font-iosevka-nerd-font"
cask "font-iosevka-nerd-font-mono"
cask "font-source-sans-pro"
cask "iterm2"
cask "java"
cask "qutebrowser"
cask "rstudio"
cask "skim"
cask "slack"
cask "spectacle"
cask "spotify"
mas "1Password 7", id: 1333542190
mas "AdGuard for Safari", id: 1440147259
mas "Elmedia Player", id: 937759555
mas "NordVPN IKE", id: 1116599239
mas "Spark", id: 1176895641
mas "Xcode", id: 497799835
