#!/usr/bin/env zsh

function conda () {
  unset -f conda
  # >>> conda initialize >>>
  #!! Contents within this block are managed by 'conda init' !!
  __conda_setup="$('/usr/local/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
    eval "$__conda_setup"
  unset __conda_setup
  conda "${@}"
}

# Local Variables:
# mode: sh-script
# sh-basic-offset: 2
# End:
