#!/usr/bin/env zsh

function conda() {
  unset -f conda
  __conda_setup="$('/usr/local/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
  if [ $? -eq 0 ]; then
    eval "$__conda_setup"
  else
    if [ -f "/usr/local/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
      . "/usr/local/Caskroom/miniconda/base/etc/profile.d/conda.sh"
    else
      export PATH="/usr/local/Caskroom/miniconda/base/bin:$PATH"
    fi
  fi
  unset __conda_setup
  conda "${@}"
}

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# End:
