#!/usr/bin/env zsh

function knitit() {
  /usr/local/bin/emacs \
    --batch \
    -l org "${DOTFILES}/config/emacs/dotemacs.org" \
    -f org-babel-tangle
}

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# End:
