#!/usr/bin/env zsh

nuke() {
  local dry_run
  zparseopts -E -- n=dry_run

  if [[ -z "${dry_run}" ]]; then
    read -r "response?Are you sure? [y/N] "
    if [[ "${response}" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
      git clean -dfx \
        && git submodule foreach --recursive git clean -dfx
    fi
  else
    git clean -dfxn \
      && git submodule foreach --recursive git clean -dfxn
  fi
}

# Local Variables:
# mode: sh-script
# sh-indentation: 2
# End:
