#!/usr/bin/env zsh

pyenv() {
    unset -f pyenv
    eval "$(command pyenv init -)"
    if [[ -n "${ZSH_PYENV_LAZY_VIRTUALENV}" ]]; then
        eval "$(command pyenv virtualenv-init -)"
    fi
    pyenv "${@}"
}

# Local Variables:
# mode: sh-script
# sh-basic-offset: 2
# End:
