#!/usr/bin/env zsh

function time-shell(){
  if [[ -e "$(command -v hyperfine)" ]]; then
    hyperfine -i --warmup 10 -- '$SHELL -i -c exit'
  else
    for i in {1..10}; do
      /usr/bin/time $SHELL -i -c exit
    done
  fi
}

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# End:
