#!/usr/bin/env zsh

function vbox() {
  local pause
  local resume
  local kill
  zparseopts -E p=pause r=resume k=kill

  if [[ -n "${pause}" ]]; then
    VBoxManage controlvm "CS6290 Project VM" pause --type headless
  elif [[ -n "${resume}" ]]; then
    VBoxManage controlvm "CS6290 Project VM" resume --type headless
  elif [[ -n "${kill}" ]]; then
    VBoxManage controlvm "CS6290 Project VM" poweroff --type headless
  else
    VBoxManage startvm "CS6290 Project VM" --type headless
  fi
}

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# End:
