#!/usr/bin/env zsh

function vterm_cmd() {
  if [ -n "$TMUX" ]; then
    # tell tmux to pass the escape sequences through
    # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
    printf "\ePtmux;\e\e]51;E"
  elif [ "${TERM%%-*}" = "screen" ]; then
    # GNU screen (screen, screen-256color, screen-256color-bce)
    printf "\eP\e]51;E"
  else
    printf "\e]51;E"
  fi

  printf "\e]51;E"
  local r
  while [[ $# -gt 0 ]]; do
    r="${1//\\/\\\\}"
    r="${r//\"/\\\"}"
    printf '"%s" ' "$r"
    shift
  done
  if [ -n "$TMUX" ]; then
    # tell tmux to pass the escape sequences through
    # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
    printf "\007\e\\"
  elif [ "${TERM%%-*}" = "screen" ]; then
    # GNU screen (screen, screen-256color, screen-256color-bce)
    printf "\007\e\\"
  else
    printf "\e\\"
  fi
}

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# End:
