#!/usr/bin/env bash

yabai -m config debug_output on

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.15
yabai -m config window_shadow                float

yabai -m config window_border                on
yabai -m config window_border_width          5
yabai -m config window_border_placement      inset
yabai -m config active_window_border_color   0xff98971a
yabai -m config normal_window_border_color   0xff928374
yabai -m config insert_window_border_color   0xffcc241d

yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.98
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  2
yabai -m config bottom_padding               5
yabai -m config left_padding                 2
yabai -m config right_padding                2
yabai -m config window_gap                   2

# window rules
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
#yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Karabiner EventViewer" app="^Karabiner-.*$" manage=off

# float all Emacs child-frames
yabai -m rule --add label="Emacs Childframes" app="^Emacs$" title="^(  —  \(.*\))$" manage=off border=off topmost=on

yabai -m rule --add label=emacs app="Emacs" space=1 display=2
yabai -m rule --add label=iterm app="iTerm2" space=1 display=1
yabai -m rule --add label=firefox app="Firefox" space=1 display=1
yabai -m rule --add app="Slack" space=2
yabai -m rule --add app="Spotify" space=2
yabai -m rule --add app="Messages" space=2

# signals
# yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
# yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
# add a signal that floats a window created by these apps when it's the only window
# yabai -m signal --add event=window_created action="yabai -m window --focus ${YABAI_WINDOW_ID}"
# yabai -m signal --add event=window_created app="^Emacs$" action="yabai -m window --focus last"
